spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todolist?serverTimezone=Europe/Moscow&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: se_user
    password: se_user
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    root: INFO
